import { StyleSheet, Platform } from 'react-native';

export const colors = {
  bg: '#F8FAFC', primary: '#0F766E', headerText: '#FFFFFF', textDark: '#0F172A', 
  textLight: '#64748B', white: '#FFFFFF', chipBg: '#F1F5F9', chipSelectedBg: '#0F766E', 
  chipText: '#475569', chipSelectedText: '#FFFFFF', success: '#10B981', dangerText: '#EF4444', scanBtnColor: '#8B5CF6' 
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.bg },
  mainWrapper: { flex: 1, padding: 15, overflow: 'hidden' }, // Giảm padding ngoài
  splitContainer: { flex: 1, flexDirection: 'row', width: '100%', maxWidth: 1400, alignSelf: 'center', gap: 15 }, // Giảm gap
  formContainer: { flex: 1, backgroundColor: colors.white, padding: 16, paddingRight: 8, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 10, display: 'flex' },
  cartContainer: { flex: 1, backgroundColor: '#F8FAFC', borderRadius: 12, borderWidth: 1, borderColor: '#CBD5E1', display: 'flex', flexDirection: 'column', overflow: 'hidden' },
  cartHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E2E8F0', padding: 12, borderBottomWidth: 1, borderBottomColor: '#CBD5E1' },
  cartTitle: { fontSize: 15, fontWeight: '800', color: colors.textDark, marginLeft: 8, flex: 1 },
  cartBadge: { backgroundColor: colors.primary, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  cartBadgeText: { color: colors.white, fontSize: 12, fontWeight: '800' },
  emptyCart: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },
  cartItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.white, padding: 12, borderRadius: 10, marginBottom: 10, borderWidth: 1, borderColor: '#E2E8F0' },
  addToTempBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#F0FDFA', paddingVertical: 12, borderRadius: 10, borderWidth: 1, borderColor: colors.primary, marginTop: 10 },
  addToTempText: { color: colors.primary, fontSize: 14, fontWeight: '800' },
  submitButton: { backgroundColor: colors.primary, paddingVertical: 16, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' }, 
  submitText: { color: colors.white, fontSize: 15, fontWeight: '800' },
  autocompleteDropdown: { position: 'absolute', top: '100%', left: 0, right: 0, backgroundColor: colors.white, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 10, marginTop: 4, zIndex: 1000, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 12, elevation: 5 },
  autoCompleteItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: '#F1F5F9' },
  scanButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: colors.scanBtnColor, paddingVertical: 12, borderRadius: 10, marginBottom: 15 },
  scanButtonText: { color: colors.white, fontSize: 14, fontWeight: '800' },
  aiSuggestBox: { marginBottom: 15, backgroundColor: '#FAF5FF', padding: 12, borderRadius: 10, borderWidth: 1, borderColor: '#E9D5FF' },
  aiSuggestTitle: { fontSize: 13, fontWeight: '700', color: '#7E22CE', marginBottom: 8 },
  aiChip: { backgroundColor: colors.white, paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: '#D8B4FE', marginRight: 8, marginBottom: 8 },
  aiChipText: { fontSize: 13, color: '#6B21A8', fontWeight: '700' },
  autoScheduleBox: { backgroundColor: '#F0FDFA', padding: 12, borderRadius: 10, marginBottom: 15, borderWidth: 1, borderColor: '#CCFBF1' },
  autoTitle: { fontSize: 13, fontWeight: '700', color: colors.primary, marginBottom: 8 },
  subLabel: { fontSize: 12, color: colors.textDark, marginBottom: 4, fontWeight: '600' },
  miniInput: { backgroundColor: colors.white, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, borderColor: '#E2E8F0' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.6)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: colors.white, width: '85%', maxWidth: 350, borderRadius: 16, padding: 20, elevation: 10 }, 
  modalTitle: { fontSize: 16, fontWeight: '800', color: colors.textDark, textAlign: 'center', marginBottom: 15 },
  pickerContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', height: 180, backgroundColor: '#F8FAFC', borderRadius: 12, paddingVertical: 10, borderWidth: 1, borderColor: '#E2E8F0' },
  pickerColumn: { flex: 1, alignItems: 'center', height: '100%' }, 
  pickerHeader: { fontSize: 13, fontWeight: '700', color: colors.textLight, marginBottom: 5 },
  scrollArea: { width: '100%', height: '100%', ...Platform.select({ web: { scrollbarWidth: 'thin', scrollbarColor: `${colors.primary} transparent` } }) }, 
  scrollContent: { paddingVertical: 80 }, 
  pickerItem: { paddingVertical: 8, alignItems: 'center', borderRadius: 8, marginHorizontal: 10 }, 
  pickerItemActive: { backgroundColor: colors.primary },
  pickerText: { fontSize: 16, color: colors.textLight, fontWeight: '500' }, 
  pickerTextActive: { fontSize: 20, fontWeight: '800', color: colors.white },
  pickerSeparator: { fontSize: 26, fontWeight: '800', color: colors.primary, marginHorizontal: 10, marginBottom: 15 },
  modalActions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20, gap: 10 },
  modalBtnCancel: { flex: 1, paddingVertical: 12, alignItems: 'center', backgroundColor: '#F1F5F9', borderRadius: 8 }, 
  modalBtnCancelText: { color: colors.textDark, fontWeight: '700', fontSize: 13 },
  modalBtnAdd: { flex: 1, paddingVertical: 12, alignItems: 'center', backgroundColor: colors.primary, borderRadius: 8 }, 
  modalBtnAddText: { color: colors.headerText, fontWeight: '800', fontSize: 13 },
  toastContainer: { position: 'absolute', top: 30, right: 20, backgroundColor: colors.success, paddingVertical: 10, paddingHorizontal: 16, borderRadius: 8, flexDirection: 'row', alignItems: 'center', zIndex: 1000, elevation: 5 },
  toastText: { color: colors.white, fontSize: 13, fontWeight: '700', marginLeft: 8 },
  appHeader: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.primary, paddingVertical: 12, paddingHorizontal: 20, elevation: 4 },
  backButton: { marginRight: 15, padding: 5 }, 
  logoCircleHeader: { width: 30, height: 30, borderRadius: 10, backgroundColor: '#E0F2FE', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  headerTitle: { fontSize: 16, fontWeight: '800', color: colors.headerText, marginBottom: 2 }, 
  subTitle: { fontSize: 12, color: '#CCFBF1', fontWeight: '500' },
  rowGroup: { flexDirection: 'row' },
  inputGroup: { marginBottom: 15 }, 
  label: { fontSize: 13, fontWeight: '700', color: colors.textDark, marginBottom: 6 },
  asterisk: { color: colors.dangerText },
  input: { backgroundColor: colors.white, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: colors.textDark },
  chipsContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2 }, 
  chip: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 14, backgroundColor: colors.chipBg, borderRadius: 20, borderWidth: 1, borderColor: '#E2E8F0' }, 
  chipSelected: { backgroundColor: colors.chipSelectedBg, borderColor: colors.chipSelectedBg }, 
  chipText: { fontSize: 13, color: colors.chipText, fontWeight: '600' }, 
  chipTextSelected: { color: colors.chipSelectedText, fontWeight: '800' },
  timeChipSelected: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 12, backgroundColor: colors.primary, borderRadius: 20 }, 
  chipTextSelected: { color: colors.white, fontSize: 13, fontWeight: '700' },
  timeChipAdd: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 12, backgroundColor: '#F0FDFA', borderRadius: 20, borderWidth: 1, borderColor: colors.primary, borderStyle: 'dashed' }
});